title: Test GitHub Page
author:
  name: fishberg
  email: 
description: > # this means to ignore newlines until "show_excerpts:"
    My test description
show_excerpts: false # set to true to show excerpts on the homepage

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

minima:
  skin: dark
  date_format: "%b %-d, %Y"

#plugins:
# - jekyll-feed
# - jekyll-seo-tag
